[package]
name = "VisuModiRam"
description = "Debugging tools for STM32 to visualize or modify variables on RAM"
authors = ["Takaaki-MATSUZAWA"]
version = "0.3.0"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Takaaki-MATSUZAWA/VisuModiRam"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["persistence"]
persistence = ["eframe/persistence", "egui/persistence", "serde"]

[dependencies]
eframe = { version = "0.30.0" }
probe-rs = "0.29.0"
env_logger = "0.10.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
regex = {version = "1.10.6"}
serde = { version = "1.0.190", optional = true, features = ["derive"] }
egui = { version = "0.30.0", features = [
  "callstack",
  "log",
] }
egui_extras = { version = "0.30.0", features = ["all_loaders"] }
egui_plot = { version = "0.30.0" }
shellexpand = "2.1.2"
sensorlog = "1.0.0"
rfd = "0.12.1"
use = "0.0.1-pre.0"
erased-serde = "0.4.1"
anyhow = "1.0.90"
stopwatch = "0.0.7"
# egui-modal = "0.2.3"  # Temporarily disabled due to version conflicts
ron = "0.8.1"
# egui_gauge = "0.1.2"  # Temporarily disabled due to version conflicts
ddbug_parser = { git = "https://github.com/gimli-rs/ddbug.git", rev = "b7d6d6a0382f2d7e2d7db9b1ed8450a42740e2c7" }

[[bin]]
name = "VisuModiRam"
path = "src/main.rs"
